firstName = input("Как вас зовут? ")
lastName = input("Какая у вас фамилия? ")
location = input("Где вы находитесь? ")
age = input("Сколько вам лет? ")
print("Здравствуйте, " + firstName, lastName + "! location + " – место где вы находитесь и вам" + age + лет.")
